---
- name: Calculator App deployment
  hosts: local
  vars:
    img_name: "darklordrises/spe_miniproj"
    img_tag: "latest"
    calculator_container: "calculator_app"
  tasks:
    - name: Remove a container if exists
      community.docker.docker_container:
        name: "{{ calculator_container }}"
        state: absent
      ignore_errors: yes
    
    - name: Pull the latest image
      community.docker.docker_image:
        name: "{{ img_name }}"
        tag: "{{ img_tag }}"
        source: pull
    
    - name: Run the container
      community.docker.docker_container:
        name: "{{ calculator_container }}"
        image: "{{ img_name }}:{{ img_tag }}"
        state: started
        restart_policy: no
        detach: true
        